# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.1
  - nightly

codecov: true

addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib

env:
	matrix:
	  - PYTHON=python3 # python 3.5
	
	matrix:
	  allow_failures:
	    - julia: nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

## uncomment the following lines to override the default test script
script:
 - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test("MLToys", coverage=true)'

notifications:
  email: false

